language: node_js
node_js:
- 6
- 7
- 8
- 10
before_install:
  - npm install -g --unsafe-perm homebridge
script:
  - DEBUG=* timeout --preserve-status --kill-after 30s --signal SIGINT 20s homebridge --debug --no-qrcode --user-storage-path ./test-configuration --plugin-path ./ ; test $? == 130
jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '6'
    deploy:
      provider: npm
      edge: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_API_TOKEN"
      on:
        tags: true
        branch: master
