name: Main
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - name: install homebridge
      run: npm install -g --unsafe-perm homebridge
      shell: bash
    - name: test plugin configuration
      run: DEBUG=* timeout --preserve-status --kill-after 30s --signal SIGINT 20s homebridge --debug --no-qrcode --user-storage-path ./test-configuration --plugin-path ./ ; test $? == 130
      shell: bash